name: '[Push] Sync'
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request: # only used for sync jobs to preprod and uat
    types: closed
    branches:
      - preprod
      - uat
concurrency:
  group: sync-${{ github.event_name }}
  cancel-in-progress: true
env:
  CACHE_FOLDER: slack_sync_post
  CACHE_FILE: slack_sync_thread_ts
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: #! due to matrix, all actions must be in the same sync job
        ENV: [preprod, uat]
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate_token
        with:
          app-id: ${{ secrets.SF_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.SF_GITHUB_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - uses: fregante/setup-git-user@v2
      - run: git fetch
      - run: git checkout ${{ matrix.ENV }}

      # git rebase
      - run: git rebase ${{ github.ref_name }}
        id: rebase
        continue-on-error: true
      - run: git rebase --abort
        if: steps.rebase.outcome != 'success'
        continue-on-error: true

      # fallback to merge if rebase fails
      - run: git merge ${{ github.ref_name }}
        if: steps.rebase.outcome != 'success'
        id: merge
        continue-on-error: true

      #! force push is needed, due to rewriting commit history by rebasing
      - run: git push origin HEAD:${{ matrix.ENV }} --force
        id: push
        if: steps.rebase.outcome == 'success' || steps.merge.outcome == 'success'
        continue-on-error: true

      # Delete sync branch if existing
      - name: '[Fallback] Delete Sync Branch "sync/${{ matrix.ENV }}"'
        if: steps.push.outcome != 'success'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          branches: sync/${{ matrix.ENV }}
          soft_fail: true

      # Create new branch
      - name: '[Fallback] Create Sync Branch "sync/${{ matrix.ENV }}"'
        if: steps.push.outcome != 'success'
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          branch: sync/${{ matrix.ENV }}
          sha: ${{ github.sha }}

      - run: sleep 5 # wait for any existing PR to be closed
        if: steps.push.outcome != 'success'

      # Create Pull Request
      - name: '[Fallback] Create Pull Request'
        if: steps.push.outcome != 'success'
        id: create-pr
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          FROM_BRANCH: sync/${{ matrix.ENV }}
          TO_BRANCH: ${{ matrix.ENV }}
          PULL_REQUEST_TITLE: '[SYNC] Auto-merge failed from ${{ github.ref_name }} ‚Üí ${{ matrix.ENV }}, please review and merge manually'
          PULL_REQUEST_BODY: |
            This pull request was automatically created because the automatic rebase and merge from ${{ github.ref_name }} ‚Üí ${{ matrix.ENV }} failed due to a merge conflicts. Please review and merge manually.

            # Validation

            To start validation, run `/retry` in a comment.

      - name: '[Fallback] Get Repo Name'
        uses: MariachiBear/get-repo-name-action@v1.3.0
        if: steps.push.outcome != 'success' && vars.SF_SLACK_ENABLED == 'true'
        id: repo-name

      # Post to Slack
      # TOOO: re-use subflow.slack.yml
      - name: '[Fallback] Post to Slack'
        id: slack-sync-post
        if: steps.push.outcome != 'success' && vars.SF_SLACK_ENABLED == 'true'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ vars.SF_SLACK_SYNC_CHANNEL_ID }}
          payload: |
            {
              "blocks": [{"type":"header","text":{"type":"plain_text","text":"[${{ env.REPO_NAME }}] Sync failed ‚Üí ${{ env.TO_BRANCH }}","emoji":true}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Status*\n${{ env.STATUS }}"},{"type":"mrkdwn","text":"*${{ env.EDITED_BY }}*\n<https://github.com/${{ github.actor }}|${{ github.actor }}>"}],"accessory":{"type":"overflow","options":[{"text":{"type":"plain_text","text":"üñ•Ô∏è Open PR"},"url":"https://github.com/${{ github.repository }}/pull/${{ env.PULL_REQUEST_NUMBER }}"},{"text":{"type":"plain_text","text":"ü§ì View Logs"},"url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"},{"text":{"type":"plain_text","text":"ü§ñ Open Repo"},"url":"https://github.com/${{ github.repository }}"}]}}],
              "text": "[Sync Failure] ${{ github.ref_name }} ‚Üí ${{ matrix.ENV }}",
              "unfurl_links": false,
              "unfurl_media": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SF_SLACK_BOT_TOKEN }}
          REPO_NAME: ${{ steps.repo-name.outputs.repository-name }}
          TO_BRANCH: ${{ matrix.ENV }}
          STATUS: üî¥ Not merged
          EDITED_BY: Opened By
          PULL_REQUEST_NUMBER: ${{ steps.create-pr.outputs.PULL_REQUEST_NUMBER }}

      - run: mkdir -p ${{ env.CACHE_FOLDER }}
        if: steps.push.outcome != 'success' && vars.SF_SLACK_ENABLED == 'true'
      - run: echo -n "${{ steps.slack-sync-post.outputs.ts }}" >> ${{ env.CACHE_FOLDER }}/${{ env.CACHE_FILE }}
        if: steps.push.outcome != 'success' && vars.SF_SLACK_ENABLED == 'true'
      - uses: actions/cache/save@v4
        if: steps.push.outcome != 'success' && vars.SF_SLACK_ENABLED == 'true'
        with:
          path: ${{ env.CACHE_FOLDER }}
          key: ${{ env.CACHE_FILE }}-${{ steps.create-pr.outputs.PULL_REQUEST_NUMBER }}

  update-sync-log-post:
    name: Update Sync Log Post
    if: github.event_name == 'pull_request' && contains(fromJSON('["sync/preprod", "sync/uat", "sync/dev"]'), github.head_ref) && vars.SF_SLACK_ENABLED == 'true'
    permissions:
      actions: read
      contents: write
      id-token: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Delete Sync Branch "${{ github.head_ref }}"'
        uses: dawidd6/action-delete-branch@v3
        if: contains(github.triggering_actor, '[bot]') == false
        with:
          branches: ${{ github.head_ref }}
          soft_fail: true

      - uses: actions/cache/restore@v4
        id: cache-thread-ts
        with:
          path: ${{ env.CACHE_FOLDER }}
          key: ${{ env.CACHE_FILE }}-${{ github.event.pull_request.number }}

      - run: echo "ts=$(cat ${{ env.CACHE_FOLDER }}/${{ env.CACHE_FILE }})" >> $GITHUB_OUTPUT
        id: slack-post
        if: steps.cache-thread-ts.outputs.cache-hit == 'true'
        continue-on-error: true

      - uses: MariachiBear/get-repo-name-action@v1.3.0
        if: steps.cache-thread-ts.outputs.cache-hit == 'true'
        id: repo-name

      # Post to Slack
      - name: 'Update Slack Error Post'
        id: slack-sync-post
        if: steps.cache-thread-ts.outputs.cache-hit == 'true'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ vars.SF_SLACK_SYNC_CHANNEL_ID }}
          update-ts: ${{ steps.slack-post.outputs.ts }}
          payload: |
            {
              "blocks": [{"type":"header","text":{"type":"plain_text","text":"[${{ env.REPO_NAME }}] Sync failed ‚Üí ${{ env.TO_BRANCH }}","emoji":true}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Status*\n${{ env.STATUS }}"},{"type":"mrkdwn","text":"*${{ env.EDITED_BY }}*\n<https://github.com/${{ github.actor }}|${{ github.actor }}>"}],"accessory":{"type":"overflow","options":[{"text":{"type":"plain_text","text":"üñ•Ô∏è Open PR"},"url":"https://github.com/${{ github.repository }}/pull/${{ env.PULL_REQUEST_NUMBER }}"},{"text":{"type":"plain_text","text":"ü§ì View Logs"},"url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"},{"text":{"type":"plain_text","text":"ü§ñ Open Repo"},"url":"https://github.com/${{ github.repository }}"}]}}],
              "unfurl_links": false,
              "unfurl_media": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SF_SLACK_BOT_TOKEN }}
          REPO_NAME: ${{ steps.repo-name.outputs.repository-name }}
          TO_BRANCH: ${{ github.base_ref }}
          STATUS: ${{ github.event.pull_request.merged && '‚úÖ Merged' || 'üü° Closed (not merged)'}}
          EDITED_BY: ${{ github.event.pull_request.merged && 'Merged By' || 'Closed By'}}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
